sonar.projectKey=LukSantana_NexusBot
sonar.organization=luksantana
sonar.projectName=NexusBot

sonar.sources=packages/shared/src,packages/bot/src,packages/backend/src,packages/frontend/src
sonar.tests=packages/frontend/tests
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx,**/*.spec.ts

sonar.typescript.lcov.reportPaths=packages/backend/coverage/lcov.info,packages/bot/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,packages/backend/src/public/**,packages/frontend/test-results/**,packages/shared/src/generated/**

sonar.javascript.lcov.reportPaths=packages/backend/coverage/lcov.info,packages/bot/coverage/lcov.info
